name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: [27.1, 27.2, 28.1, 28.2, 29.1, 29.2, 29.3, 29.4, 30.1]
        # TODO: Revert back to just the melpa check.  Blocked by
        # https://github.com/purcell/package-lint/issues/289
        check: [load-file, byte-compile, checkdoc]
    steps:
      - uses: purcell/setup-emacs@v6.0
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v4
      - uses: leotaku/elisp-check@master
        with:
          check: ${{ matrix.check }}
          file: '*.el'
          warnings_as_errors: true
